all: part1.exe part2.exe part3.exe part4.exe

part1.exe: part1.c
	gcc -o part1.exe part1.c

part2.exe: part2.c
	gcc -o part2.exe part2.c

part3.exe: part3.c
	gcc -o part3.exe part3.c

part4.exe: part4.c
	gcc -o part4.exe part4.c

